### ISSUE TITLE
How to change css styles of modal window?

### ISSUE THREAD

**Issue by kentforth** [davodaslanifakor/modaltor#14]
**How can I change css styles of modal window?**

Let's say I want to change height of modal. 
How can I do that?

**Comment by davodaslanifakor** [comment]
I'm sorry for the delay. 
in ASAP add new options.

**Comment by davodaslanifakor** [comment]
You can add style this class

```css 
.modal-vue-panel {
    height: 300px;
}
```
